In [1]:
from collections import defaultdict, Counter
import pandas

def to_int(x, y):
    return int(x), y

def get_milestones(text):
    with open(text) as f:
        milestones = dict([
            to_int(*s.strip().split("#"))
            for s in f
        ])
    return milestones

## TNAH

In [2]:
stud_mls = get_milestones("tnah.milestones.txt")
stud_txt = defaultdict(str)
full_txt = ""

with open("training_students.txt") as f:
    current_text = None
    for no, line in enumerate(f):
        if no in stud_mls:
            current_text = stud_mls[no]
        stud_txt[current_text] += line.strip()
        stud_txt["Full"] += line.strip()
        


counters = {
    title: Counter(text)
    for title, text in stud_txt.items()
}
majs = {
    title: Counter([
        el
        for key, value in cnt.items()
        for el in (
            value * ["Uppercase"]
            if key.isupper() 
            else 
            value * ["Lowercase"]
        )
    ])
    for title, cnt in counters.items()
}
    
diversity = [
    [
        title,
        dict([
            ("size", len(text)), 
            ("dataset", "students"), 
            ("classes", len(set(text))), 
            *majs[title].items(), 
            *counters[title].items()
        ])
    ]
    for title, text in stud_txt.items()
]

## Pinche

In [3]:
pinc_mls = get_milestones("pinche.milestones.txt")
pinc_txt = defaultdict(str)

with open("training full.txt") as f:
    current_text = None
    for no, line in enumerate(f):
        if no in pinc_mls:
            current_text = pinc_mls[no]
        pinc_txt[current_text] += line.strip()
        pinc_txt["Full"] += line.strip()
        


counters = {
    title: Counter(text)
    for title, text in pinc_txt.items()
}
majs = {
    title: Counter([
        el
        for key, value in cnt.items()
        for el in (
            value * ["Uppercase"]
            if key.isupper() 
            else 
            value * ["Lowercase"]
        )
    ])
    for title, cnt in counters.items()
}


diversity.extend([
    *[
        [
            title,
            dict([
                ("size", len(text)), 
                ("dataset", "pinche"), 
                ("classes", len(set(text))), 
                *majs[title].items(), 
                *counters[title].items()
            ])
        ]
        for title, text in pinc_txt.items()
    ]
])

## Dataframe

In [5]:
df = pandas.DataFrame([d[1] for d in diversity], index=[d[0] for d in diversity]).fillna(0)
df.columns = [
    5*[""]+(len(df.columns)-5)*["Char"],
    df.columns
]
df.to_csv("datasets-characters.csv")
#df["Char"].div(df[("", "size")], axis=0)
df

                                                           Char                \
              size   dataset classes Lowercase Uppercase      u      i      t
Philippe      5413  students      64      5376        37    181    437    320
Full         69482  students     102     68866       616   2798   5433   3908
JacquesMin    7014  students      55      6975        39    266    603    435
Longis       11918  students      62     11813       105    475    998    649
Luce         12408  students      57     12317        91    474    916    667
Sixte        18459  students      65     18264       195    725   1459   1052
Pelagie       7673  students      62      7596        77    375    546    409
Euphrasie     6597  students      49      6525        72    302    474    376
Martin       78453    pinche      77     77780       673   3376   6664   5062
Full        494525    pinche      96    490413      4112  20778  41394  30619
Dialogues    97329    pinche      75     96568       761   4273   8109   5937
Brice         7134    pinche      54      7064        70    299    611    484
Giles        22743    pinche      55     22549       194    913   1960   1406
Marcel       80092    pinche      73     79429       663   3210   6456   4862
Nicolas     109364    pinche      75    108516       848   4570   9272   6797
Jerome       12320    pinche      57     12202       118    521    978    737
Benoit       65782    pinche      72     65189       593   2758   5590   4071
Alexis       21308    pinche      64     21116       192    858   1754   1263

                           ...                                               \
                          ...    ƺ    ᵈ    >    ;    7    8    [    ]    ç
Philippe      925    34.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Full        11150   631.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
JacquesMin   1221     1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Longis       2099   177.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Luce         1879   159.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Sixte        2848   260.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Pelagie      1215     0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Euphrasie     963     0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Martin      11519   738.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Full        72202  4762.0  ...  3.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
Dialogues   15132   834.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Brice         997    68.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Giles        3250   211.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Marcel      11323   888.0  ...  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Nicolas     15279  1082.0  ...  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
Jerome       1720   109.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Benoit       9682   573.0  ...  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0
Alexis       3300   259.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0


              K
Philippe    0.0
Full        0.0
JacquesMin  0.0
Longis      0.0
Luce        0.0
Sixte       0.0
Pelagie     0.0
Euphrasie   0.0
Martin      0.0
Full        1.0
Dialogues   0.0
Brice       0.0
Giles       0.0
Marcel      0.0
Nicolas     0.0
Jerome      0.0
Benoit      0.0
Alexis      1.0

[18 rows x 133 columns]